version: '2'

services:

    web:
        build:
            context: ./dockerfiles/
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app

    app:
        build:
            context: ./dockerfiles/
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        environment:
            - "DB_HOST=database"
            - "DB_PORT=3306"
            - "REDIS_HOST=cache"
            - "REDIS_PORT=6379"
        links:
            - database
            - cache

    database:
        build:
            context: ./dockerfiles/
            dockerfile: database.docker
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports:
            - "33061:3306"

    cache:
        image: redis:3.0
        ports:
            - "63791:6379"
